version: "3.9"

services:
  backend:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    container_name: bf-backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  # frontend:
  #   build:
  #     context: ../frontend
  #   container_name: bf-frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: bf-postgres
    environment:
      POSTGRES_DB: bfnavigator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
