spring.application.name=bf-navigator-service
spring.datasource.url=jdbc:postgresql://db:5432/bfnavigator
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
db.client-id=${DB_CLIENT_ID:}
db.client-secret=${DB_CLIENT_SECRET:}
google.routes.api-key=${GOOGLE_MAPS_API_KEY:}
jwt.secret=${JWT_SECRET:mySuperSuperSecretKeyThatIsLongEnough123!}
jwt.expiration=3600000
