#### Register
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "firstName": "Ilias",
  "lastName": "Doe",
  "email": "Ilias.doe-test2@example.com",
  "password": "password123",
  "accessibilityTypes": ["WHEELCHAIR"]
}


#### Login
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "Ilias@example.com",
  "password": "password123"
}


#### health
GET http://localhost:8080/actuator/health
Content-Type: application/json



